.ORIG x3000

REWIND
LD R2, INIT		; R2 = x5000
AND R4, R4, #0		; CLEAR EVEN NUMBER COUNTER
LD R0, COUNTER		; R0 = 10 LOOP COUNTER MAIN (10 VALUE)

MAIN
LDR R3, R2, #0		; LD DATA FROM ADDRESS STORE IN R2
LD R5, MASK		; R5 IS MASK FOR EVEN NUMBER CHECKING
AND R5, R5, R3		; R5 = 0 IS EVEN, R5 = 1 IS ODD
BRnp NEXT		; IF ODD, OVERLOOK COUNTER INCREMENT

ADD R4, R4, #1		; EVEN NUMBER COUNTER INCREMENT 

NEXT
ADD R2, R2, #1		; INCREMENT ADDRESS POINTER TO NEXT ADDRESS
ADD R0, R0, #-1		; DECREMENT MAIN LOOP COUNTER 
BRp MAIN		; IF NOT ENOUGH ADDRESS LOADED, LOOP TO MAIN

AND R1, R1, #0		; CLEAR R1 FOR EVEN NUMBER DISPLAY VALUE
ADD R1, R1, #1		
ADD R4, R4, #-10
BRz DISPLAY		; IF R4 = 10, OVERLOOK VALUE CORRECTION

ADD R4, R4, #10		; VALUE CORRECTION IF R4 < 10
ADD R1, R1, #-1		; VALUE CORRECTION FOR TENS NUMBER

LEA R0, MSG0		; DISPLAY FIRST HALF MESSAGE
PUTS

DISPLAY
LD R0, ASCII		
ADD R0, R0, R1		; CONVERT TENS NUMBER TO ASCII
OUT
LD R0, ASCII
ADD R0, R0, R4		; CONVERT ONES NUMBER TO ASCII
OUT

LEA R0, MSG1		; DISPLAY SECOND HALF MESSAGE
PUTS

AND R0, R0, #0
AND R1, R1, #0

POLL
LD R0, TEN
OUT
LEA R0, POLLER
PUTS
GETC
ADD R1, R0, #-10
BRz REWIND
ADD R1, R0, -8
BRz DONE
BR POLL

DONE
HALT

INIT .FILL x5000
ASCII .FILL #48
MASK .FILL #1
COUNTER .FILL #10
MSG0 .STRINGZ "THERE IS A TOTAL OF "
MSG1 .STRINGZ " EVEN NUMBER!"
POLLER .STRINGZ "AGAIN: "
TEN .FILL #10

.END