.ORIG x3000

LD R4, MASK
LD R1, VALUE

AND R5, R4, R1
BRz EVEN

LD R6, TWO		; LOAD R6 WITH AMOUNT TO SHIFT RIGHT

REWIND
LD R2, COUNTER
LD R4, SHIFT_MASK
LD R3, SHIFT_OP
AND R0, R0, #0

AGAIN
AND R5, R4, R1
BRz UPDATE

ADD R0, R0, R3

UPDATE
ADD R3, R3, R3		; SHIFT OPERAND FOR RIGHT SHIFT TO 1 BIT LEFT
ADD R4, R4, R4		; SHIFT MASK FOR RIGHT SHIFT TO 1 BIT LEFT
ADD R2, R2, #-1		; DECREMENT BIT-LENGTH COUNTER
BRp AGAIN
ADD R1, R0, #0		; TRANSFER NEW SHIFTED VALUE TO R1
ADD R6, R6, #-1		; DECREMENT RIGHT SHIFT COUNTER
BRp REWIND		; IF SHIFTED 2 BITS RIGHT, END SHIFT
STI R0, RESULT		; STORE 2-BIT RIGHT SHIFT RESULT TO LOCATION x3100
BR DONE			; END ODD BRANCH

EVEN
ADD R1, R1, R1		; LEFT SHIFT 1-BIT
ADD R0, R1, R1		; LEFT SHIFT 1-BIT
STI R0, RESULT		; STORE 2-BIT LEFT SHIFT RESULT TO LOCATION x3100

DONE
HALT

MASK .FILL x0001
SHIFT_MASK .FILL x0002 ; 0000 0000 0000 0010
SHIFT_OP .FILL x0001
COUNTER .FILL #15
TWO .FILL #2
RESULT .FILL x3100
VALUE .FILL xFFFF

.END